apiVersion: v1
kind: Secret
metadata:
  name: laravel-sa-token
  namespace: laravel-namespace
  annotations:
    kubernetes.io/service-account.name: laravel-sa
type: kubernetes.io/service-account-token